// cmd/docsgen/main.go
// Generates the body and TOC inside docs/documentation.html from DOCUMENTATION.md.
//
// The page chrome (head, nav, hero, search bar, sidebar, footer, inline CSS / JS)
// is hand-maintained in docs/documentation.html. This tool only rewrites the
// regions between the BEGIN_TOC/END_TOC and BEGIN_CONTENT/END_CONTENT markers,
// so the source of truth for documentation prose stays in DOCUMENTATION.md.
//
// Usage:
//
//	go run ./cmd/docsgen                  # rewrite docs/documentation.html in place
//	go run ./cmd/docsgen -doc DOC.md -html docs/documentation.html
package main

import (
	"bytes"
	"flag"
	"fmt"
	stdhtml "html"
	"os"
	"regexp"
	"strings"

	"github.com/yuin/goldmark"
	"github.com/yuin/goldmark/extension"
	"github.com/yuin/goldmark/parser"
	gmhtml "github.com/yuin/goldmark/renderer/html"
)

const (
	tocBegin     = "<!-- BEGIN_TOC: auto-generated by cmd/docsgen from DOCUMENTATION.md — do not edit by hand -->"
	tocEnd       = "<!-- END_TOC -->"
	contentBegin = "<!-- BEGIN_CONTENT: auto-generated by cmd/docsgen from DOCUMENTATION.md — do not edit by hand -->"
	contentEnd   = "<!-- END_CONTENT -->"
)

func main() {
	docPath := flag.String("doc", "DOCUMENTATION.md", "path to DOCUMENTATION.md")
	htmlPath := flag.String("html", "docs/documentation.html", "path to documentation.html")
	flag.Parse()

	mdBytes, err := os.ReadFile(*docPath)
	if err != nil {
		fatal("read %s: %v", *docPath, err)
	}

	// Strip the leading hand-written TOC block — the sidebar generated below
	// replaces it. Anything before the first H2 ("## Overview") is treated as
	// front matter and dropped from the rendered body.
	body := stripFrontMatter(string(mdBytes))

	htmlBody, err := renderMarkdown(body)
	if err != nil {
		fatal("render markdown: %v", err)
	}

	htmlBody = defaultCodeLanguage(htmlBody, "bash")

	wrapped, toc := wrapSectionsAndBuildTOC(htmlBody)

	pageBytes, err := os.ReadFile(*htmlPath)
	if err != nil {
		fatal("read %s: %v", *htmlPath, err)
	}
	page := string(pageBytes)

	page, err = replaceBlock(page, tocBegin, tocEnd, indent(toc, "        "))
	if err != nil {
		fatal("replace TOC: %v", err)
	}
	page, err = replaceBlock(page, contentBegin, contentEnd, indent(wrapped, "      "))
	if err != nil {
		fatal("replace content: %v", err)
	}

	if err := os.WriteFile(*htmlPath, []byte(page), 0644); err != nil {
		fatal("write %s: %v", *htmlPath, err)
	}
	fmt.Fprintf(os.Stderr, "Updated %s\n", *htmlPath)
}

func fatal(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}

// stripFrontMatter removes everything before the first "## " heading in the
// markdown source. This drops the centered <div align="center"> block, the
// "Table of Contents" line, and the "Commands:" inline list — all of which
// are reproduced as the rendered sidebar TOC, so we don't want them duplicated
// in the page body.
func stripFrontMatter(md string) string {
	re := regexp.MustCompile(`(?m)^## `)
	loc := re.FindStringIndex(md)
	if loc == nil {
		return md
	}
	return md[loc[0]:]
}

// renderMarkdown converts a markdown string to HTML using goldmark with GFM
// tables, autolinks, and unsafe HTML passthrough (DOCUMENTATION.md contains
// some inline HTML that should render through verbatim).
func renderMarkdown(md string) (string, error) {
	md = preprocessMarkdown(md)
	gm := goldmark.New(
		goldmark.WithExtensions(
			extension.GFM,
		),
		goldmark.WithParserOptions(
			parser.WithAutoHeadingID(),
		),
		goldmark.WithRendererOptions(
			gmhtml.WithUnsafe(),
		),
	)
	var buf bytes.Buffer
	if err := gm.Convert([]byte(md), &buf); err != nil {
		return "", err
	}
	return buf.String(), nil
}

// preprocessMarkdown applies a small set of transformations to bring the
// generated HTML closer to the hand-written original. Currently:
//
//   - Strip horizontal-rule lines that act as section separators in the
//     markdown source. The page chrome already provides visual separation,
//     and the original page only used <hr> between sub-commands inside the
//     Commands section.
func preprocessMarkdown(md string) string {
	// Drop standalone "---" separator lines.
	out := regexp.MustCompile(`(?m)^\s*---\s*$`).ReplaceAllString(md, "")
	return out
}

// defaultCodeLanguage adds class="language-<lang>" to any <code> directly
// inside a <pre> that doesn't already declare a language. Goldmark emits a
// bare <pre><code> for fenced blocks without an info string, but the help-text
// blocks in DOCUMENTATION.md (command usage, flag listings) read like shell
// output, so we want highlight.js to apply the bash grammar to them.
var bareCodeRe = regexp.MustCompile(`<pre><code>`)

func defaultCodeLanguage(body, lang string) string {
	return bareCodeRe.ReplaceAllString(body, `<pre><code class="language-`+lang+`">`)
}

// section represents one h2 region of the rendered documentation: an id, a
// display title, the inner HTML, and any nested h3s for the sidebar.
type section struct {
	ID    string
	Title string
	Inner string
	Subs  []subheading
}

type subheading struct {
	ID    string
	Title string
}

// h2Re matches a goldmark-generated h2 with an id attribute.
// Goldmark's auto heading IDs use simple slugs, so the ids in this output
// will be the canonical ids for the page from now on.
var (
	h2Re = regexp.MustCompile(`(?s)<h2 id="([^"]+)">(.*?)</h2>`)
	h3Re = regexp.MustCompile(`(?s)<h3 id="([^"]+)">(.*?)</h3>`)
)

// wrapSectionsAndBuildTOC takes the goldmark-rendered HTML body and:
//   - Splits it on h2 boundaries
//   - Wraps each h2 + body in <section class="docs-section" id=... data-heading=...>
//     so the existing search/scroll-spy JS keeps working
//   - Builds the sidebar TOC <li> list (h2s flat, h3s with class="toc-h3")
func wrapSectionsAndBuildTOC(body string) (string, string) {
	matches := h2Re.FindAllStringSubmatchIndex(body, -1)
	if len(matches) == 0 {
		return body, ""
	}

	var (
		out      strings.Builder
		toc      strings.Builder
		sections []section
	)

	// Anything before the first h2 is preserved verbatim (typically empty
	// after stripFrontMatter).
	if matches[0][0] > 0 {
		prefix := strings.TrimSpace(body[:matches[0][0]])
		if prefix != "" {
			out.WriteString(prefix)
			out.WriteString("\n\n")
		}
	}

	for i, m := range matches {
		id := body[m[2]:m[3]]
		titleHTML := body[m[4]:m[5]]
		title := stripTags(titleHTML)

		var end int
		if i+1 < len(matches) {
			end = matches[i+1][0]
		} else {
			end = len(body)
		}
		// Inner is everything from the h2 tag through the byte before the next h2.
		inner := body[m[0]:end]

		sec := section{
			ID:    id,
			Title: title,
			Inner: inner,
			Subs:  collectSubheadings(inner),
		}
		sections = append(sections, sec)
	}

	for _, sec := range sections {
		out.WriteString(fmt.Sprintf(
			"<section class=\"docs-section\" id=\"%s\" data-heading=\"%s\">\n",
			htmlEscape(sec.ID),
			htmlEscape(sec.Title),
		))
		out.WriteString(strings.TrimSpace(sec.Inner))
		out.WriteString("\n</section>\n\n")

		// TOC entry for the h2
		toc.WriteString(fmt.Sprintf(
			"<li><a href=\"#%s\">%s</a></li>\n",
			htmlEscape(sec.ID),
			htmlEscape(sec.Title),
		))
		// TOC entries for nested h3s (rendered as toc-h3)
		for _, sub := range sec.Subs {
			toc.WriteString(fmt.Sprintf(
				"<li><a href=\"#%s\" class=\"toc-h3\">%s</a></li>\n",
				htmlEscape(sub.ID),
				htmlEscape(sub.Title),
			))
		}
	}

	return strings.TrimRight(out.String(), "\n"), strings.TrimRight(toc.String(), "\n")
}

func collectSubheadings(htmlBody string) []subheading {
	var subs []subheading
	for _, m := range h3Re.FindAllStringSubmatch(htmlBody, -1) {
		subs = append(subs, subheading{
			ID:    m[1],
			Title: stripTags(m[2]),
		})
	}
	return subs
}

// stripTags removes inline HTML tags from a heading title so the sidebar /
// data-heading attribute renders as plain text. We unescape entities so the
// caller can re-escape with htmlEscape and avoid double-escaping.
var tagRe = regexp.MustCompile(`<[^>]+>`)

func stripTags(s string) string {
	s = tagRe.ReplaceAllString(s, "")
	s = stdhtml.UnescapeString(s)
	return strings.TrimSpace(s)
}

func htmlEscape(s string) string {
	return stdhtml.EscapeString(s)
}

// replaceBlock swaps the contents between begin and end markers (markers
// preserved). Returns an error if either marker is missing.
func replaceBlock(page, begin, end, replacement string) (string, error) {
	bIdx := strings.Index(page, begin)
	if bIdx == -1 {
		return "", fmt.Errorf("missing begin marker %q", begin)
	}
	eIdx := strings.Index(page[bIdx:], end)
	if eIdx == -1 {
		return "", fmt.Errorf("missing end marker %q", end)
	}
	eIdx += bIdx

	// Insert: keep the begin marker line, newline, replacement, newline, end marker.
	var b strings.Builder
	b.WriteString(page[:bIdx])
	b.WriteString(begin)
	b.WriteString("\n")
	b.WriteString(replacement)
	b.WriteString("\n")
	// Indentation for end marker — match the column of the begin marker so
	// the resulting HTML stays nicely aligned. We compute the indent of the
	// begin marker by walking backwards to the previous newline.
	endIndent := indentOf(page, bIdx)
	b.WriteString(endIndent)
	b.WriteString(end)
	b.WriteString(page[eIdx+len(end):])
	return b.String(), nil
}

func indentOf(s string, pos int) string {
	start := pos
	for start > 0 && s[start-1] != '\n' {
		start--
	}
	return s[start:pos]
}

// indent prepends the given prefix to every line of s, except lines that fall
// between <pre> and </pre> tags (where leading whitespace is significant and
// would render inside the code block).
func indent(s, prefix string) string {
	if s == "" {
		return s
	}
	lines := strings.Split(s, "\n")
	inPre := false
	for i, line := range lines {
		// Track <pre> state. We check the line *before* deciding whether to
		// indent it: an opening <pre> on a line still gets indented (the tag
		// itself is HTML), but the lines that follow until </pre> do not.
		opened := strings.Contains(line, "<pre")
		closed := strings.Contains(line, "</pre>")

		if !inPre && line != "" {
			lines[i] = prefix + line
		}

		switch {
		case opened && !closed:
			inPre = true
		case closed:
			inPre = false
		}
	}
	return strings.Join(lines, "\n")
}
